name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions

on:

  push:

  workflow_dispatch:

jobs:

  Explore-GitHub-Actions:

    runs-on: self-hosted

    steps:

      - run: echo "SEC ${{ secrets.MY_SECRET_NAME }} ."

      - run: echo "VAR = ${{ vars.MY_NAME }} "

      
